apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: search-ca
spec:
  isCA: true
  commonName: Search Service Internal CA
  secretName: search-ca-tls
  duration: 87600h # 10 years
  renewBefore: 8760h # 1 year
  subject:
    organizationalUnits:
    - Search Service
    - Certificate Authority
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
