apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-controller-manager
spec:
  template:
    spec:
      serviceAccountName: search-controller-manager
      automountServiceAccountToken: true
