apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: search.miloapis.com-searcher
  namespace: milo-system
spec:
  launchStage: Alpha
  includedPermissions:
    - search.miloapis.com/searchqueries.create
