# RoleBinding for leader election
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: search-controller-manager
    app.kubernetes.io/managed-by: kustomize
  name: search-controller-manager-leader-election
  namespace: search-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: search-controller-manager-leader-election
subjects:
- kind: ServiceAccount
  name: search-controller-manager
  namespace: search-system
