apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
  namespace: meilisearch-system
spec:
  interval: 5m
  timeout: 2m

  chart:
    spec:
      chart: meilisearch
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: meilisearch
        namespace: meilisearch-system
      interval: 1h

  # Values for the chart
  # https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/values.yaml
  values:
    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Environment loaded into the confingMap
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: "search-master-key" # Must be using a secret in production environment

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
