apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.search.miloapis.com
spec:
  service:
    name: search-apiserver
    namespace: search-system
    port: 443
  group: search.miloapis.com
  version: v1alpha1
  insecureSkipTLSVerify: false
  groupPriorityMinimum: 1000
  versionPriority: 15
